### PR TITLE
feat(JATS): Add decoder for `<disp-quote>`

### PR DESCRIPTION
**Pull request by rgieseke**

### CODE REVIEW

**Comment by rgieseke** [comment]
And another tiny JATS one, this adds support for decoding `<disp-quote>` elements into `QuoteBlock`.

JATS: https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/disp-quote.html
Stencila QuoteBlock: https://help.stenci.la/references/schema/QuoteBlock/

I'm reluctant about adding the `attrib` -> `cite` as i'm not sure the mapping to a citation is how `attrib` would be used (haven't seen "real-world" examples, i guess in papers `attrib` in a quote would be rare).

Adapted example without `attrib`:
```xml
<?xml version="1.0"?>
<article>
<front>
</front>
<body>
<disp-quote id="quote1">
<p>Dead flies cause the ointment of the apothecary to send forth a
stinking savor; so doth a little folly him that is in reputation
for wisdom and honour. (Ecclesiastes 10:1)</p>
</disp-quote>
</body>
</article>
```

```json
{
  "type": "Article",
  "identifiers": [],
  "title": "Untitled",
  "meta": {},
  "content": [
    {
      "type": "QuoteBlock",
      "id": "quote1",
      "content": [
        {
          "type": "Paragraph",
          "content": [
            "Dead flies cause the ointment of the apothecary to send forth a\nstinking savor; so doth a little folly him that is in reputation\nfor wisdom and honour. (Ecclesiastes 10:1)"
          ]
        }
      ]
    }
  ]
}              
```

**Comment by nokome** [comment]
Thanks @rgieseke 💯 .

A snapshot needs to be updated (one of the PLOS articles contained a block quote): https://dev.azure.com/stencila/stencila/_build/results?buildId=14382&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=1962

Also, it would be useful to consume the new jats fixture in a test (or did I miss that?). 

I can do both if you like, but not for a day or two...

**Comment by rgieseke** [comment]
I'll try to tackle that, once again i was struggling with getting the snapshot to update ... (in spite of cache clearing and using commands that worked before i think ...)

**Comment by rgieseke** [comment]
I hope that was it! (I was confused about the different directories and how the tests were supposed to work ...)

**Comment by nokome** [comment]
Looks good, thanks again!

**Pull request merged**
