### PR TITLE
fix(JATS): Allow for multiple objects in `fig`

### PR DESCRIPTION
**Pull request by rgieseke**
Currently the JATS `fig` decoder only allows for a single child element. However, there can be multiple `graphic` objects for example.

This PR seems to handle this in a general way.
I've tested it with examples taken from https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/fig.html

```xml
<?xml version="1.0"?>
<article>
  <front>
    <article-meta>
      <contrib-group />
    </article-meta>
  </front>
  <body>

    <p>Example 1</p>
    <fig id="f1" orientation="portrait" position="float">
      <graphic xlink:href="f1" />
      <attrib>Brookhaven National Laboratory</attrib>
    </fig>

    <p>Example 2</p>
    <fig id="f8" orientation="portrait" position="float">
      <label>FIG. 8.</label>
      <caption>
        <p>Time difference between events F and A as a function of the
length of entering plug for bifurcations B to BXXX, where X stands
for 0 or 1.</p>
      </caption>
      <graphic orientation="portrait" position="float" xlink:href="f8" />
    </fig>

    <p>Example 3</p>
    <fig id="F1">
      <caption>
        <title>Deaths among patients receiving day hospital care
or alternative services.</title>
        <p>
          Odds ratios of death by end of follow up were calculated by
fixed effects model. Heterogeneity between trials is presented as
&#x03C7;
          <sup>2</sup>
        </p>
      </caption>
      <alt-text>Deaths in hospitals or with alternative services</alt-text>
      <graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="fors2662.f1">
        <object-id>456472</object-id>
      </graphic>
    </fig>

    <p>Example 4</p>
    <fig id="f1" orientation="portrait" position="float">
      <label>FIG. 1.</label>
      <caption>
        <p>
          (a) Schematic of the working principles of HFM, (b) a typical application
scheme for an electric bias in HFM, (c) regulation the conformations and
dynamics (trapping, concentration, and sudden stretching) of λ-DNA molecules
in HFM, and (d) schematic of the trapping location regulation (enhanced online).
[URL:
          <ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.1063/1.4762852.1">
http://dx.doi.org/10.1063/1.4762852.1</ext-link>
          ]
          <alternatives>
            <media id="v1" mime-subtype="avi" mimetype="video" orientation="portrait" position="anchor" specific-use="original-format" xlink:href="v1" />
            <media mime-subtype="mpeg" mimetype="video" orientation="portrait" position="anchor" specific-use="archival-format" xlink:href="v1" />
            <media mime-subtype="x-flv" mimetype="video" orientation="portrait" position="anchor" specific-use="online-format" xlink:href="v1" />
          </alternatives>
        </p>
      </caption>
      <graphic orientation="portrait" position="float" xlink:href="f1" />
      <graphic id="f1a" orientation="portrait" position="float" xlink:href="dummy1.png" />
      <graphic id="f1b" orientation="portrait" position="float" xlink:href="dummy2.png" />
      <graphic id="f1c" orientation="portrait" position="float" xlink:href="dummy3.png" />
      <graphic id="f1d" orientation="portrait" position="float" xlink:href="dummy4.png" />
    </fig>

    <p>Example 5</p>
    <fig id="f3" position="float">
      <label>FIG. 3.</label>
      <caption>...</caption>
      <alternatives>
        <graphic specific-use="print" xlink:href="1.4821168.figures.highres.f3.zip" />
        <graphic specific-use="online" xlink:href="1.4821168.figures.online.f3.jpg" />
      </alternatives>
    </fig>

  </body>
  <back>
    <app-group />
  </back>
</article>
```
This produces the following JSON:
```json
{
  "type": "Article",
  "identifiers": [],
  "title": "Untitled",
  "meta": {},
  "content": [
    {
      "type": "Paragraph",
      "content": [
        "Example 1"
      ]
    },
    {
      "type": "Figure",
      "id": "f1",
      "content": [
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/f1",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ],
        [
          "Brookhaven National Laboratory"
        ]
      ]
    },
    {
      "type": "Paragraph",
      "content": [
        "Example 2"
      ]
    },
    {
      "type": "Figure",
      "id": "f8",
      "caption": [
        {
          "type": "Paragraph",
          "content": [
            "Time difference between events F and A as a function of the\nlength of entering plug for bifurcations B to BXXX, where X stands\nfor 0 or 1."
          ]
        }
      ],
      "label": "FIG. 8.",
      "content": [
        [
          "FIG. 8."
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/f8",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ]
      ]
    },
    {
      "type": "Paragraph",
      "content": [
        "Example 3"
      ]
    },
    {
      "type": "Figure",
      "id": "F1",
      "caption": [
        {
          "type": "Heading",
          "depth": 1,
          "content": [
            "Deaths among patients receiving day hospital care\nor alternative services."
          ]
        },
        {
          "type": "Paragraph",
          "content": [
            "Odds ratios of death by end of follow up were calculated by\nfixed effects model. Heterogeneity between trials is presented as\nχ",
            {
              "type": "Superscript",
              "content": [
                "2"
              ]
            }
          ]
        }
      ],
      "content": [
        [
          "Deaths in hospitals or with alternative services"
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/fors2662.f1",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ]
      ]
    },
    {
      "type": "Paragraph",
      "content": [
        "Example 4"
      ]
    },
    {
      "type": "Figure",
      "id": "f1",
      "caption": [
        {
          "type": "Paragraph",
          "content": [
            "(a) Schematic of the working principles of HFM, (b) a typical application\nscheme for an electric bias in HFM, (c) regulation the conformations and\ndynamics (trapping, concentration, and sudden stretching) of λ-DNA molecules\nin HFM, and (d) schematic of the trapping location regulation (enhanced online).\n[URL: ",
            {
              "type": "Link",
              "target": "http://dx.doi.org/10.1063/1.4762852.1",
              "content": [
                "\nhttp://dx.doi.org/10.1063/1.4762852.1"
              ]
            },
            "]\n"
          ]
        },
        {
          "type": "MediaObject",
          "contentUrl": "test.json.media/v1",
          "format": "video/avi"
        },
        {
          "type": "MediaObject",
          "contentUrl": "test.json.media/v1",
          "format": "video/mpeg"
        },
        {
          "type": "MediaObject",
          "contentUrl": "test.json.media/v1",
          "format": "video/x-flv"
        }
      ],
      "label": "FIG. 1.",
      "content": [
        [
          "FIG. 1."
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/f1",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/dummy1.png",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/dummy2.png",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/dummy3.png",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/dummy4.png",
            "format": "",
            "meta": {
              "inline": false
            }
          }
        ]
      ]
    },
    {
      "type": "Paragraph",
      "content": [
        "Example 5"
      ]
    },
    {
      "type": "Figure",
      "id": "f3",
      "caption": [
        "..."
      ],
      "label": "FIG. 3.",
      "content": [
        [
          "FIG. 3."
        ],
        [
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/1.4821168.figures.highres.f3.zip",
            "format": "",
            "meta": {
              "inline": false,
              "usage": "print"
            }
          },
          {
            "type": "ImageObject",
            "contentUrl": "test.json.media/1.4821168.figures.online.f3.jpg",
            "format": "",
            "meta": {
              "inline": false,
              "usage": "online"
            }
          }
        ]
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by rgieseke** [comment]
The output looks reasonable to me. There are some issues, `alternatives` could appear in the caption as well as in the main content.
Is there a way to define alternatives in the Stencila schema already? I think that could be useful.
With the previous approach there should be no regression as an existing `alternatives` would be set to the content field.

**Comment by rgieseke** [comment]
I looked into updating the fixtures (if you you want to accept the change like this).

I ran

`npx jest src/codecs/jats/`

 › 10 snapshots failed from 1 test suite. Inspect your code changes or run `npm run npx -- -u` to update them.

But this command doesn't work. I couldn't figure out how to update them.

**Comment by nokome** [comment]
Thanks @rgieseke !

> › 10 snapshots failed from 1 test suite. Inspect your code changes or run npm run npx -- -u to update them.
> But this command doesn't work. I couldn't figure out how to update them.

That's strange, I get a slightly different message: 

```
› 10 snapshots failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.
```

In anycase, `npx jest src/codecs/jats -u` should hopefully work for you.

When I run that I see a couple of problems:

- the `label` is still in the `content` -(see your JSON output above)
- in eLife JATS they add a `<object-id pub-id-type="doi">10.7554/eLife.30274.002</object-id>` element within `<fig>` which should ideally be parsed to `Figure.identifiers`
- `<alternatives>` are not being handled properly

> Is there a way to define alternatives in the Stencila schema already? I think that could be useful.

Not generally (i.e. represented in the schema). I agree is could be useful for certain types, particularly `ImageObject` but in leiu of that, for now I suggest we take the first alternative.

I am happy to go ahead and make the above fixes on this PR as well as add your example as a fixture.

**Comment by rgieseke** [comment]
Thanks, i'll try to figure out why it wasn't displaying the right message for updating. (It did for me in an earlier PR i think.)
It's a joy to contribute to an project with such great documentation and though out automation - even if there might be an occasional 'works-on-my-machine :-)

As for `label`, it is next to `content`, isn't it?
```json
"label": "FIG. 1.",
      "content": [
 ```
 
 The "meta" fields in JATS 1.2 for fig are 
```
<object-id> Object Identifier, zero or more
<label> Label (of an Equation, Figure, Reference, etc.), zero or one
<caption> Caption of a Figure, Table, etc., zero or one
<abstract> Abstract, zero or more
<kwd-group> Keyword Group, zero or more
```
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/fig.html

So adding `object-id` there would make sense.

Thanks for taking this further (it's getting late here ...)

**Comment by nokome** [comment]
I've made a few changes and added a test fixture. Will merge. Please create another issue / PR if still not quite expected output

**Review by nokome — APPROVED** [review]

**Pull request merged**
