### PR TITLE
perf(CLI): Improve startup time by using dynamic module loading

### PR DESCRIPTION
**Pull request by alex-ketch**
Uses module loading short-circuiting logic and dynamic imports to improve startup times by ~300%

```
# Before dynamic imports
real    0m15.570s
user    0m15.370s
sys     0m2.827s

# JSON only
real    0m5.228s
user    0m4.381s
sys     0m1.513s

# Short Circuit module resolution by extName
real    0m7.641s
user    0m5.987s
sys     0m2.134s

# Short circuit & iterative dynamic loading
--from json '{"key": "value"}' --to json -
real    0m5.209s
user    0m4.388s
sys     0m1.464s


package.json --to json -
real    0m5.918s
user    0m4.879s
sys     0m1.756s


# ONLY iterative dynamic loading
src/codecs/xlsx/__fixtures__/simple-table.xlsx --to csv -
real    0m8.238s
user    0m7.573s
sys     0m1.766s

package.json --to json -
real    0m13.053s
user    0m12.954s
sys     0m2.448s
```

### CODE REVIEW

**Comment by alex-ketch** [comment]
Did a follow up test using a tool I came across on Twitter called [`0x`](https://github.com/davidmarkclements/0x). The resulting flamegraph seems to indicate that we spent ~38% of our time inside AJV.js. Could be the next place of optimization to look into.

---

Results of the following command attached below
`npx 0x -- node dist/src/cli convert '{}' --from json --to json - `

[enocoda convert flamegraph-2019-06-24.zip](https://github.com/stencila/encoda/files/3321864/enocoda.convert.flamegraph-2019-06-24.zip)

 
Screen Shot 2019-06-24 at 13 07 11

**Comment by nokome** [comment]
Useful tool! Yeah, I agree, the synchronous loading and compilation of JSON schemas that we are doing in `util/index.ts` should be the next candidate for optimisation.

Ajv has an asynchronous mode for validation. I had used it for an earlier version of the `validate` and `mutate` functions, but it's a little bit tricky because you have to have fallbacks to resolve the location of the schema at runtime. That's why I reverted to synchronous - temporarily. I've just tried to find that old code, to no avail, but will create an issue with the general gist of it.

**Comment by nokome** [comment]
Added comment on an approach to optimising Ajv usage: https://github.com/stencila/encoda/issues/60#issuecomment-505139926

**Comment by alex-ketch** [comment]
Thanks for documenting the code sections to look into next @nokome
I think this PR can be merged into `reorg` branch. I'm looking into the tests we disabled.
I think (more like hope 🤞) I've made progress regarding the mysteriously failing tests, and will try to make a separate PR to `reorg` with them reenabled today.

**Comment by nokome** [comment]
OK, going ahead and merging now.

**Pull request merged**
