### PR TITLE
feat(TypeGuards): Remove type guards, instead import them from Schema

### PR DESCRIPTION
**Pull request by alex-ketch**
Relates to https://github.com/stencila/schema/pull/98

### CODE REVIEW

**Comment by alex-ketch** [comment]
Due to the schema inheritance changes, using `Entity` instead of `Thing` there were a couple fields on the `Link` schema the I removed. 
The changes are isolated to a commit that I can revert if we'd like to add them back to `Link`/`Entity`. What do you think @nokome?

**Comment by nokome** [comment]
Ahhh yes, the `meta` issue. I added this property to `Thing` as an escape hatch - so that we could experiment with adding additional properties to any node (in Encoda, or elsewhere), without having to update `schema` and still keeping `additionalProperties: false` (in the JSON Schema). The intention with `meta` is to give tooling developers the flexibility to experiment with new properties, and then if those experiments are fruitful, to elevate those properties to being first class properties.

My first use case, as a tooling developer myself here in Encoda, was to experiment with adding `import` and `export` "directives" to `Link` nodes, so that we could do things like this in Markdown:

```markdown
This [`odt`](article-complex-ex1.out.odt){export=complex} file was generated from the simple example.
```

That commit will break that (it will just ignore the export directive). The export/import/include directives are handled in `process.ts`. I feel that this is still experimental and needs some more considered design. So I think it should be kept as experimental and therefore that those directives should stay in `meta`.

In the case of `Thing.description`, we were using that for storing link `title` attributes (from Markdown, but could also come from `<a href="...", title="...>`). So it's a different matter to `meta`.

So I suggest that:

- In schema, I move `meta` from `Thing` to `Entity` and document the above rationale for that property
- In schema, I add `title: string` to `Link`.
- you revert that commit, and make the change from using `description` to using `title`

**Comment by alex-ketch** [comment]
@nokome sounds good, will revert ↩️ and update :)

**Comment by nokome** [comment]
For the sake of simplicity, I'm going to make those change to Schema on master. Then `npm link` to get this and #176 working locally and then merge them both into `master`. Otherwise it feels like we're chasing our tails a bit :dog2: :poodle:

**Comment by alex-ketch** [comment]
@nokome Thanks, that makes sense. I've updated this branch with the necessary changes, so feel free to merge/adjust as needed.

**Pull request closed without merging**
